- fxa/_utils.py
- fxa/errors.py
- fxa/oauth.py
- fxa/tests/test_oauth.py
A couple of suggested tweaks to the oauth client API:
* Create a new error hierarchy for scope errors, since they're not really a client *or* server error
* Don't allow calling the low-level scope_matches function with required=None
* Make client_id and client_secret be properties of the oauth.Client object
@leplatrem thoughts?
> Some oauth client API tweaks

- fxa/oauth.py
- fxa/tests/test_oauth.py
The v1 suffix is set on the oauth_uri configuration as explained in https://oauth-stable.dev.lcip.org/console/clients
> Fix FxA OAuth server URLs

- fxa/core.py
- fxa/crypto.py
- fxa/oauth.py
- fxa/tests/test_core.py
- fxa/tests/test_oauth.py
This adds `get_identity_assertion()` to the core client class, and `authorize_code()` and `authorize_token()` methods to the oauth client class.  They're useful for simulating a full oauth flow.
@tarekziade r?
Closes #7 and #8.
> Add helper methods for getting assertions and oauth tokens

- fxa/_utils.py
- fxa/profile.py
- fxa/tests/test_profile.py
Here's a super simple API for talking to the profile server, https://github.com/mozilla/fxa-profile-server/.  Pass in an OAuth token with appropriate scope, get back the associated profile info.  We might come up with some more over-arching "user" abstraction in future, but I think this will be a handy start for reliers.
@Natim r?
> Add basic API for accessing user profile data.

- fxa/oauth.py
- fxa/tests/test_oauth.py
Our cache classes should return unicode strings at this stage.
> Cache classes should expose Unicode.

- setup.py
This is to prevent installation failure with PIP when an UTF-8 characters is present in the README or the CHANGES files.
> Read UTF-8 files in setup.

- fxa/cache.py
- fxa/oauth.py
- fxa/plugins/requests.py
- fxa/tests/test_cache.py
- fxa/tests/test_oauth.py
- fxa/tests/test_requests_auth_plugin.py
This is to prevent calling the Firefox Account infrastructure too much when using the same Auth backend for multiple requests.
> Add basic cache functionality to the Auth Plugins.

- fxa/__init__.py
- setup.py
Otherwise, some tools (e.g. fedora automatic packaging, loads) are not able to
use PyFxA as a dependency due to the fact that they don't install it in
a standard way.
r? @tarekziade
> Do not rely on the package to be installed.

- fxa/crypto.py
Using `default_backend()` relies on the entrypoints feature of setuptools, which
is broken somehow on loads. In order to have PyFxA compatible with loads, this
loads the backends without relying on them (and uses open ssl by default).
cc @tarekziade @rfk
> Do not load crypto backends using entrypoints.

- fxa/_utils.py
@Natim this sends the library and platform version information as part of the user-agent header, what do you think?  It should make it easier for us to pick out PyFxA specifically in our logs.
> Include more version and platform information in user-agent header.

- fxa/core.py
- fxa/tests/test_core.py
You do not actually need username and password to use this function. I am currently using it to confirm certain fxa accounts using the data (uid and code) from the confirmation link in the email.
Do you think it makes sense for upstream too? If not, please ignore this :smile:
Cheers,
Juanito
> add verify_email_code(uid, code) to client

- CHANGES.txt
- fxa/__init__.py
- setup.py
This change have been made previously to comply with loadsv1 which is not supported anymore. I would like to revert it because it makes releases a lot easier.
> Improve PyFxA releases

- fxa/__init__.py
- fxa/__main__.py
- fxa/cache.py
- fxa/tests/test_core.py
While looking into #48, I noticed that the current default cache implementation touches every item in the cache on every `get()`, in order to enforce expiry.  This PR makes two changes:
* Use a queue for processing expiry, so we don't have to touch every item.
* Use an explicit Lock to ensure we're thread-safe by default.
@leplatrem does this seem worthwhile?
> Avoid walking entire cache on each get, and make it thread-safe.

- fxa/core.py
- fxa/oauth.py
- fxa/tests/test_core.py
- fxa/tests/test_oauth.py
Here's an attempt to fix #50; @kewisch if you get a chance to try it out I'd appreciate it.
The idea is to make it easy to include the `?service=foo` query parameter when signing an identity certificate.  You can pass it manually, or you can just pass in a `Session` object and let the oauth client do it for you.  The code here:
https://github.com/kewisch/pyamo/blob/master/pyamo/utils.py#L67-L71
Would become just:
```
session = client.login(username, password)
oauth_client = fxa.oauth.Client(server_url=oauth_url)
return oauth_client.authorize_code(session, scope, client_id)
```
Thoughts?
> Make it easy to include `?service=foo` when signing a certificate.

- fxa/tests/test_core.py
- fxa/tests/utils.py
Hopefully fixes #60; @chartjes let me know if this helps?
> Tell test runners not to collect the TestEmailAccount class.

- fxa/__main__.py
- fxa/oauth.py
- fxa/tests/test_core.py
- fxa/tests/test_oauth.py
- fxa/tests/test_requests_auth_plugin.py
- fxa/tests/test_tools.py
- fxa/tools/bearer.py
- fxa/tools/create_user.py
WIP, needs tests, but fixes #58.
@Natim with this change, I can successfully run the following to get a bearer token:
```
python -m fxa --bearer --account-server="https://latest-keys.dev.lcip.org/auth" --oauth-server="https://oauth-latest-keys.dev.lcip.org/" --scopes="profile https://identity.mozilla.org/apps/notes" --client-id=c6d74070a481bc10 -c --use-pkce
```
It doesn't have support for generating scoped keys yet, though.
> Add basic support for PKCE and keys_jwk in OAuth flow.

- fxa/_utils.py
- fxa/tests/test_oauth.py
This copies the testcases from [1] and updates our scope-checking code to ensure they pass.  Several were incorrectly matching where they should have failed.  I've omitted some of the low-level validation from [1] in favour of just getting the basic rules up and running before cutting a new tokenserver release.
[1] https://github.com/mozilla/fxa-shared/pull/21
> Improve scope-matching logic based on new FxA testcases.

- dev-requirements.txt
- fxa/core.py
- fxa/tests/test_core.py
Uploading this for comment. I've added support for 2fa/totp, but I'm struggling with the test. My understanding was that all I need to do to enable it is to create the token and possibly verify a code, and then it should work.
I'm probably confusing the "verified" state, I'm not sure if that is just for verifying the account after creation, or if it is the state the session is in after the TOTP code was verified.
The tests fail on the verifying step with "A TOTP token not found", so it seems the token creation failed somehow, or did not stick.
Would be delighted for the right hints on how to actually enable 2fa on an account.
> Add support for TOTP

- setup.py
This will allow dependency checkers like pyup.io to know that PyFxA is Python 3 compatible.
> Add trove classifiers for versions of Python

- fxa/_utils.py
I suspect this is the cause of #73, and would also explain why that issue was only sporadically reproducible. There's probably a bigger cleanup we could do here to avoid having to make this check at all, but this small fix seems like a good start.  @pmac r?
> Don't modify self.server_url when making a request.

- .travis.yml
- dev-requirements.txt
- fxa/oauth.py
- fxa/tests/test_oauth.py
ref mozmeao/basket#256
@rfk - r?
cc @pmac
> Support `ttl` when trading a code for an access token.

- CHANGES.txt
- fxa/core.py
Fixes #82, at least in my manual testing. I think that some new security heuristics on the server are flagging login requests without a "reason" field as invalid.
> Send `reason` and `verificationMethod` fields in login request.

- fxa/_utils.py
- fxa/oauth.py
- fxa/tests/test_oauth.py
Fixes #84. I also filed https://github.com/mozilla/fxa/pull/5888 to update the FxA docs in this regard.
@fzzzy r?
> Loosen JWT `typ`-matching rules to conform to RFC recommendations.

- fxa/_utils.py
Potential fix for the connection errors.
See https://github.com/mozmeao/basket/issues/1187
> Add retries to the APIClient session

- .circleci/config.yml
- README.rst
- dev-requirements.txt
- fxa/_utils.py
- fxa/constants.py
- fxa/core.py
- fxa/crypto.py
- fxa/tests/test_core.py
- fxa/tests/test_crypto.py
- fxa/tests/utils.py
- pytest.ini
Our APIs now support a new key stretching approach (ie key stretching V2)
- Adds support for key stretching V2
- The salt is now a random value and not the user's email
- There are now 650000 iterations during the stretch instead of 1000.
- Test have been parameterized to run with both V1 and V2 key stretch approaches
- Effort has been taken to ensure that V1 approach still works
- Key stretch v1 is still the default mode. In order to activate V2, the client must be provided the `key_stretch_version=2` argument.
- Tests work again!
- Support for python 2 dropped
- Python 2 ci tests removed
- Adds doc about setup and running tests
- Updates references to Firefox Accounts to be Mozilla Accounts
- Unpins versions in dev-requirements, so libraries can update
- Updates 'stable' urls to point …
> Support Key Stretching Version 2

- README.rst
The section has been using markdown, but the file is in RST format. I have updated the section with the appropriate RST formatting. No content has been updated.
The section should renders as the following:
> Fix formatting from "Contributing to PyFxA"

- README.rst
Nit: Let's use `code:: bash` for all code blocks so that there's a copy icon available. In addition, wee don't need `$` character to denote the prompt in the code blocks.
> Use the same formatting for all code blocks
